//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDJ.UCommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public brand()
        {
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        [Required]
        [Display(Name ="Brand Name")]
        [StringLength(200, MinimumLength =3)]
        public string name { get; set; }
        [Display(Name = "Description")]
        [DataType(DataType.MultilineText)]
        [StringLength(2000,MinimumLength =3)]
        public string description { get; set; }
        [Required]
        public string origin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
    }
}
