//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDJ.UCommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class comment
    {
        public int Id { get; set; }

        [Required]
        public int ProductId { get; set; }
        [Required]
        public int UserId { get; set; }
        [DataType(DataType.DateTime)]
        public System.DateTime DateTime { get; set; }
        
        public string Ip { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string Comment1 { get; set; }
        [Required]
        [Display(Name ="Product")]
        public virtual product product { get; set; }
        
        public virtual user user { get; set; }
    }
}
