//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDJ.UCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Ip { get; set; }
        public string message1 { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
