//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDJ.UCommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdjUCommerceEntities : DbContext
    {
        public bdjUCommerceEntities()
            : base("name=bdjUCommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminUser> adminUsers { get; set; }
        public virtual DbSet<archieve> archieves { get; set; }
        public virtual DbSet<brand> brands { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<closeType> closeTypes { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<condition> conditions { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<logInHistory> logInHistories { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productClosed> productCloseds { get; set; }
        public virtual DbSet<productImage> productImages { get; set; }
        public virtual DbSet<productLike> productLikes { get; set; }
        public virtual DbSet<productRating> productRatings { get; set; }
        public virtual DbSet<productVerified> productVerifieds { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userVerified> userVerifieds { get; set; }
        public virtual DbSet<vwNonVerifiedUser> vwNonVerifiedUsers { get; set; }
        public virtual DbSet<vwVerifiedUser> vwVerifiedUsers { get; set; }
    }
}
