//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDJ.UCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productClosed
    {
        public int id { get; set; }
        public int ProductId { get; set; }
        public System.DateTime DateTime { get; set; }
        public int ClosingTypeId { get; set; }
    
        public virtual closeType closeType { get; set; }
        public virtual product product { get; set; }
    }
}
